basic_project/basic_project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
# from django.conf import settings
# from django.conf.urls.static import static


handler404 = 'basic_project.views.custom_404'
handler500 = 'basic_project.views.custom_500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('error/<str:message>', views.error, name='error-page'),
    path('note/', include('note_app.urls')),
    path('contact_app/', include('contact_app.urls')),
    path('news/', include('scraping_app.urls')),
    path('file/', include('file_app.urls')),
    path('users/', include('users.urls'))
]

basic_project/file_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'file_app'

urlpatterns = [
    path('upload/', views.upload_file, name='upload_file'),
    path('files/', views.file_list, name='file_list'),
]

basic_project/note_app/urls.py
"""
URL configuration for the ``note_app`` module.

This module contains all the URL routes for the Notes feature of the Personal Assistant app.
Each route maps a URL path to its corresponding view function.

Routes are grouped into:
- Notes operations (create/edit/delete/view)
- Tag operations (create/edit/delete/filter)

App name:
    ``note_app``

Example:
    Use with Django's reverse() function:
        >>> reverse("note_app:note-main")

Attributes:
    app_name (str): The application namespace.
    urlpatterns (list): List of URL route definitions.
"""

from django.urls import path
from . import views


app_name = 'note_app'

#: List of URL patterns for note and tag operations
urlpatterns = [
    #: URL pattern to access the main dashboard of notes
    path('main/', views.main, name='note-main'),

    #: URL pattern to create a new tag or list existing tags
    path('tag/', views.tag, name='note-tag'),

    #: URL pattern to view notes associated with a specific tag
    path('tag/<str:tag_name>', views.search_by_tag, name='notes-by-tag'),

    #: URL pattern to edit a tag by its ID
    path('tag/edit/<int:tag_id>/', views.edit_tag, name='notes-tag-edit'),

    #: URL pattern to delete a tag by its ID
    path('tag/delete/<int:tag_id>/', views.delete_tag, name='notes-tag-delete'),

    #: URL pattern to create a new note
    path('note/', views.note, name='note'),

    #: URL pattern to edit an existing note by ID
    path('note/edit/<int:note_id>/', views.note, name='note-edit'),

    #: URL pattern to update the color of a note
    path('note/color/<int:note_id>/', views.update_note_color, name='note-color-update'),

    #: URL pattern to delete a note
    path('note/delete/<int:note_id>/', views.note_delete, name='note-delete'),
]

basic_project/scraping_app/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.currency_view, name='main'),
]

basic_project/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('signup-success/', views.signup_success, name='signup-success'),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate_user'),

    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('password-reset/done/', views.password_reset_done, name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
]

basic_project/basic_project/views.py
from django.shortcuts import render, redirect


def main(request):
    return render(request, 'index.html')


def error(request, message, status=404):
    return render(
        request,
        'error.html',
        {
            'message': message
        },
        status=status,
    )


def custom_404(request, exception):
    return error(request, "⛔ Page not found (404)")


def custom_500(request):
    return error("💥 Server error (500)")

basic_project/basic_project/templates/partials/top_navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom sticky-top shadow-sm">
<!-- <nav class="navbar navbar-expand-lg border-bottom bg-body-tertiary shadow-sm"> -->
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom"> -->
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main' %}">📝 Personal Assistant</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <!-- Ліва частина меню -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active{% endif %}"
             href="{% url 'main' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.resolver_match.namespace == 'note_app' %}active{% endif %}" href="#" id="notesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Notes
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'note_app:note-main' %}">📋 All Notes</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'note_app:note' %}">➕ Add Note</a></li>
              <li><a class="dropdown-item" href="{% url 'note_app:note-tag' %}">🏷️ Add/Edit Tag</a></li>
            </ul>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.resolver_match.namespace == 'note_app' %}active{% endif %}" href="#" id="notesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Contacts
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'contact_app:main' %}">
                <i class="bi bi-person-lines-fill me-1"></i> 
                View Contacts
                </a></li>
              <li><a class="dropdown-item" href="{% url 'contact_app:add_contact' %}">➕ Add Contact</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.resolver_match.namespace == 'note_app' %}active{% endif %}" href="#" id="notesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              File Manager
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'file_app:file_list' %}">
                <i class="bi bi-folder2-open me-1"></i> 
                Browse Files
                </a></li>
              <li><a class="dropdown-item" href="{% url 'file_app:upload_file' %}">➕ Upload File</a></li>
            </ul>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'news:main' %}">News</a>
          </li>          
        {% endif %}
      </ul>

      <!-- Theme switcher -->
      <form class="d-flex align-items-right ms-3">
        <label for="theme-select" class="form-label me-2 mb-0">🌓</label>
        <select class="form-select form-select-sm" id="theme-select" onchange="changeTheme(this.value)">
          <option value="auto">Auto</option>
          <option value="light">Light</option>
          <option value="dark">Dark</option>
        </select>
      </form>

  </div>
</form>

      <!-- Права частина меню (user info/login/logout) -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false">
              👤 {{ user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>